### ISSUE TITLE
Faild to compile with VS2010

### ISSUE THREAD

**Issue by lwttai** [utelle/SQLite3MultipleCiphers#11]
VS2010 is not providing inttypes.h
`1>ClCompile:
1>  sqlite3mc.c
1>d:\sqlite3multipleciphers\src\sqlite3mc_vfs.c(15): fatal error C1083: Cannot open include file: 'inttypes.h': No such file or directory
1>
1>Build FAILED.`

**Comment by utelle** [comment]
Thanks for reporting. I will look into this. Maybe the issue can be fixed easily by using `#include "mystdint.h"` instead of `#include <inttypes.h>`, but I have to check that.

However, the "better" option for you would be to upgrade your compiler. VS2010 is rather dated.

**Comment by lwttai** [comment]
There also tons of strange errors, maybe some #if #endif not paird cause by some include?
```
1>d:\sqlite3multipleciphers\src\cipher_config.c(739): error C2143: syntax error : missing ';' before 'type'
1>d:\sqlite3multipleciphers\src\cipher_config.c(740): error C2143: syntax error : missing ';' before 'type'
1>d:\sqlite3multipleciphers\src\cipher_config.c(741): error C2143: syntax error : missing ';' before 'type'
...
1>d:\sqlite3multipleciphers\src\codecext.c(336): error C2143: syntax error : missing ';' before 'const'
1>d:\sqlite3multipleciphers\src\codecext.c(337): error C2143: syntax error : missing ';' before 'type'
```

**Comment by utelle** [comment]
Well, I think the reason for those errors is also that VS2010 is a really dated compiler. VS2010 doesn't like variable definitions with intervening code as supported by recent C standards.

Again, I will look into this later today.

**Comment by utelle** [comment]
Commit f349308b5957310add759a27da34d87fb1339e8a should fix the compilation problem with VS2010.
