### ISSUE TITLE
Documentation `SQLCipher` table

### ISSUE THREAD

**Issue by 05nelsonm** [utelle/SQLite3MultipleCiphers#115]
Shouldn't the default for `legacy` be a `4`, not `0`?

![image](https://github.com/utelle/SQLite3MultipleCiphers/assets/44778092/2381b02e-dc6a-4022-b10e-3ae8a4799490)

**Comment by utelle** [comment]
> Shouldn't the default for `legacy` be a `4`, not `0`?

No. For **all** ciphers the default mode is **non-legacy** (that is, `legacy = 0`). However, databases created in _non-legacy_ mode are usually not compatible with databases encrypted with the _original_ product (like [SQLCipher](https://www.zetetic.net/sqlcipher)). If compatibility with the original product is required, you will have to set the parameter `legacy` explicitly to a non-zero value. For details see the documentation of the [legacy cipher mode](https://utelle.github.io/SQLite3MultipleCiphers/docs/ciphers/cipher_legacy_mode/).

**Comment by 05nelsonm** [comment]
Ah ok. tyvm for the explanation!
