### ISSUE TITLE
Sqlite3 See encrypted db

### ISSUE THREAD

**Issue by neervanbiqs** [utelle/SQLite3MultipleCiphers#117]
I need to decrypt an encrypted db with sqlite see aes128 knowing the password. I decrypted it successfully with Sqlite Manager (just pasted the password without any cipher params). 
But I need to have capability to decrypt it with 3d party software using windows sqlite3.dll.
I tried sqlite3mc_x64.dll, it works well, but it cant decrypt my db with any cipher. I think it because sqlite3mc uses aes128cbc but sqlite see uses aes128ofb.
So where I can find sqlite3.dll with see implementation (or maybe old source code that was free)?

**Comment by utelle** [comment]
> I need to decrypt an encrypted db with sqlite see aes128 knowing the password. I decrypted it successfully with Sqlite Manager (just pasted the password without any cipher params).

If _**sqlite see aes128**_ stands for [**SQLite SEE**](https://sqlite.org/purchase/see) and you know the password, then you should continue to use your _Sqlite Manager_ tool. [**SQLite SEE**](https://sqlite.org/purchase/see) is a commercial extension with closed source.

> But I need to have capability to decrypt it with 3d party software using windows sqlite3.dll.

As said **SQLite SEE** is closed source. That is, it is unlikely that you will find any 3rd party software capable of decrypting SEE encrypted databases. But if you do, chances are very high that it will be an illegal source.

> I tried sqlite3mc_x64.dll, it works well, but it cant decrypt my db with any cipher. I think it because sqlite3mc uses aes128cbc but sqlite see uses aes128ofb.

Most likely the AES mode is not the only difference between **SQLite SEE** and **SQLite3 Multiple Ciphers**. Key derivation and initial vectors are probably also different.

**SQLite3 Multiple Ciphers** supports the following cipher schemes that are all _Open Source_:

- [wxSQLite3](https://github.com/utelle/wxsqlite3): AES 128 Bit CBC - No HMAC
- [wxSQLite3](https://github.com/utelle/wxsqlite3): AES 256 Bit CBC - No HMAC
- [sqleet](https://github.com/resilar/sqleet): ChaCha20 - Poly1305 HMAC
- [SQLCipher](https://www.zetetic.net/sqlcipher/): AES 256 Bit CBC - SHA1/SHA256/SHA512 HMAC
- [System.Data.SQLite](http://system.data.sqlite.org/): RC4

That is, the [**SQLite SEE**](https://sqlite.org/purchase/see) cipher scheme is **not supported**. And that will not change in the future!

> So where I can find sqlite3.dll with see implementation (or maybe old source code that was free)?

The only encryption scheme that ever was distributed with SQLite was the RC4-based scheme that was included in [System.Data.SQLite](http://system.data.sqlite.org/). However, even that RC4 encryption scheme was **never _officially_ supported**. And  [**SQLite SEE**](https://sqlite.org/purchase/see) was never freely available.

Sorry, your wish cannot be fulfilled by **SQLite3 Multiple Ciphers** - neither now nor in the future.
