### ISSUE TITLE
Feature Request: C#/.NET SQLitePCLRaw provider

### ISSUE THREAD

**Issue by jammerxd** [utelle/SQLite3MultipleCiphers#120]
Create a nuget packge that implements the SQLitePCLRaw provider as a bundle so that c# applications can use SQLite3MultipleCiphers.

https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/custom-versions?tabs=netcore-cli

**Comment by utelle** [comment]
> Create a nuget packge that implements the SQLitePCLRaw provider as a bundle so that c# applications can use SQLite3MultipleCiphers.

In principle, I would be ready to create such a package. However, when I do a search for `SQLitePCLRaw` on [nuget.org](https://www.nuget.org) I get a really long list with [148 entries](https://www.nuget.org/packages?q=SQLitePCLRaw) (as of today). There are different packages for different platforms. So, what sort of nuget support do you have in mind?

**Comment by jammerxd** [comment]
Well if you read the entire doc linked - the SQLitePCLRaw is for the raw/base compiled binaries for various platforms that bind with the .NET core provider.

So yes, there's hundreds because there's about half a dozen existing providers with various implementations of sqlite (SQLCipher is one of them) - and then multiply that by the number of platforms and other sub-dependend packages.

So we'd have to do exactly what the SQLCipher packages do starting with the ground up.

**Comment by utelle** [comment]
> Well if you read the entire doc linked - the SQLitePCLRaw is for the raw/base compiled binaries for various platforms that bind with the .NET core provider.
> 
> So yes, there's hundreds because there's about half a dozen existing providers with various implementations of sqlite (SQLCipher is one of them) - and then multiply that by the number of platforms and other sub-dependend packages.
> 
> So we'd have to do exactly what the SQLCipher packages do starting with the ground up.

If I restrict the search on [nuget.org](https://www.nuget.org) to _SQLCipher_ related packages, I still get 40 entries. This is still an overwhelmingly high number.

**Comment by jammerxd** [comment]
Again, read the documentation from Microsoft that descripts what packages we need to create.

https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite/custom-versions?tabs=netcore-cli

**Comment by utelle** [comment]
If someone is in a hurry, this [recipe for using SQLite3MultipleCiphers with SQLitePCLRaw](https://github.com/shamork/SQLitePCLRaw.multipleciphers) may be a good start.

I will take a look at the [SQLitePCL.raw project](https://github.com/ericsink/SQLitePCL.raw). Maybe generating packages for _SQLite3MultipleCiphers_ can be integrated into that project somehow.

**Comment by utelle** [comment]
Actually, the project [ericsink/SQLitePCL.raw project](https://github.com/ericsink/SQLitePCL.raw) depends on the project [ericsink/cb](https://github.com/ericsink/cb). The latter creates the binaries of the native SQLite library for all supported platforms.

In a first step I tried to adjust the project **cb** locally to support _SQLite3 Multiple Ciphers_. I needed several attempts to accomplish that task, but eventually I succeeded.

Before continuing with the integration of _SQLite3 Multiple Ciphers_ into _SQLitePCL.raw_ we have to clarify which compile time options should be used with _SQLite3 Multiple Ciphers_. For the binaries included in the releases of _SQLite3 Multiple Ciphers_ I enable quite a number of SQLite features. The **cb** project uses a much smaller list of defines, namely

```C
#define SQLITE_ENABLE_COLUMN_METADATA
#define SQLITE_ENABLE_FTS3_PARENTHESIS
#define SQLITE_ENABLE_FTS4
#define SQLITE_ENABLE_FTS5
#define SQLITE_ENABLE_JSON1
#define SQLITE_ENABLE_MATH_FUNCTIONS
#define SQLITE_ENABLE_RTREE
#define SQLITE_ENABLE_SNAPSHOT
#define SQLITE_DEFAULT_FOREIGN_KEYS 1
```

Below is a list of options that are normally enabled for _SQLite3 Multiple Ciphers_ in addition to the options listed above. However, probably not all are useful in the C#/.Net context:

```C
/* Required / recommended options */
#define CODEC_TYPE CODEC_TYPE_CHACHA20
#define SQLITE_TEMP_STORE 2
#define SQLITE_USE_URI
#define SQLITE_SECURE_DELETE

/* Disable support for double-quoted literals */
#define SQLITE_DQS 0

/* Useful extensions */
#define SQLITE_ENABLE_EXTFUNC
#define SQLITE_ENABLE_GEOPOLY
#define SQLITE_ENABLE_REGEXP
#define SQLITE_ENABLE_SERIES
#define SQLITE_ENABLE_SHA3
#define SQLITE_ENABLE_UUID
#define SQLITE_SOUNDEX

/* File oriented extensions */
#define SQLITE_ENABLE_CSV
#define SQLITE_ENABLE_VSV
#define SQLITE_ENABLE_FILEIO

/* Session extension (not usuable without support in the wrapper) */
#define SQLITE_ENABLE_DESERIALIZE
#define SQLITE_ENABLE_SESSION

/* User authentication extension */
#define SQLITE_USER_AUTHENTICATION 1
```
**Notes**: A few comments regarding the above options:

- **Required / recommended options**
  These options will be kept.
- **Disable support for double-quoted literals**
  The default value for this option is **_3_**, that is, _allowing_ double-quoted literals. However, that is really bad SQL style and even the SQLite developer team recommends to use the value **_0_** for disabling double-quoted literals.
- **Useful extensions**
  I would keep these options as they can all be used from SQL, but of course they increase the size of the binaries.
- **File oriented extensions**
  Personally, I would drop these options.
- **Session extension**
  These options would require dedicated support in the wrapper that is currently not available. Therefore I would drop these options for now.
- **User authentication extension**
  This feature is rarely used. Therefore I would drop this option.

Any comments from your side?

**Comment by jammerxd** [comment]
Let me review and I'll let you know.

**Comment by utelle** [comment]
In the meantime I created a [fork](https://github.com/utelle/cb) of project [ericsink/cb](https://github.com/ericsink/cb), added a branch `sqlitemc`, and adjusted the build scripts. I used a certain subset of SQLite compile time options; we can adjust that later on.

The adjusted [GitHub workflow](https://github.com/utelle/cb/actions/runs/6446509578) completes successfully. However, inspecting the workflow runs there are some warnings and errors:

- All platforms, Setup.NET
  - Warning: .NET Core 3.1 is no longer supported ... (the original project has these warnings, too)
- macOS, Build
  - Warnings "gethostuuid() is disabled." for **all** SQLite variants
  - Warnings "-framework Security: 'linker' input unused" (maybe I added this compiler option at too many places)
- Windows, Build
  - Errors for architecture `x64_arm`

I used the workflow file of the project [ericsink/cb](https://github.com/ericsink/cb) with only minor adjustments (adding SQLite3MC, and excluding the tests). The workflow puts the resulting binaries in a separate branch called `staging`. At the moment I don't know how and when these binaries are transferred to the main branch.

**Comment by jammerxd** [comment]
Yeah .net core 3.1 isn't a thing anymore - if you want to target .net we'll need to target the following:

.net standard 2.0/2.1

.net 6, .net 7, .net 8 (currently in CR1)

windows does have an arm64 version - and we should look into why the arm64 architecture of sqlite isn't compiling.

I'd say we should enable as many features as we can with sqlitemc with regard to the following:

**Disable support for double-quoted literals**
I'm not sure about the side effects of disabling double quotes, but if it's disabled in the others, then it'd make sense to disable for the nuget package.
**Useful extensions**
I agree in keeping those extensions enabled.
**File oriented extensions**
I also agree with dropping them - but I haven't used them before either so I'm not really qualified on why it should or should not be enabled.
**Session extension**
Understood, if this isn't something that's supported we would either need to add it to the wrapper or disable it. I'm in favor of disabling until we have it functional andthen maybe re-evaluate.
**User authentication extension**
If it's rarely used sure. I'd be in favor of keeping it if it doesn't require any modifications - this is something I'd personally explore using with what I'm currently working on.

**Comment by utelle** [comment]
> Yeah .net core 3.1 isn't a thing anymore - if you want to target .net we'll need to target the following:
> 
> .net standard 2.0/2.1
> 
> .net 6, .net 7, .net 8 (currently in CR1)

This is sort of a misunderstanding. _SQLitePCL.raw_ supports all these targets (AFAIK). And the underlying native SQLite binaries are independent of the .net version. However, the GitHub workflow for generating the native libraries uses .net core 3.1. Most likely this could be changed. However, there might be a reason why the _SQLitePCL.raw_ folks haven't done that yet.

> windows does have an arm64 version - and we should look into why the arm64 architecture of sqlite isn't compiling.

Again a misunderstanding. The native library for **arm64** _**is**_ generated, but the one for **arm** is _**not**_. The reason is that some function declarations for the Neon support seem to be incorrect. And that's a bit strange, because all non-Windows builds for **arm** succeed.

> I'd say we should enable as many features as we can with sqlitemc with regard to the following:

In principle, I agree.

> **Disable support for double-quoted literals**
> I'm not sure about the side effects of disabling double quotes, but if it's disabled in the others, then it'd make sense to disable for the nuget package.

The real problem here is that the default settings of SQLite **allow** double-quoted literals. _SQLitePCL.raw_ does not set this option so far, so that all other _SQLitePCL.raw_ providers allow double-quoted literals. Therefore we maybe shouldn't use this option either - even if double-quoted literals are really bad SQL style.

> **File oriented extensions**
> I also agree with dropping them - but I haven't used them before either so I'm not really qualified on why it should or should not be enabled.

These extensions are very useful in a SQLite shell, but are less common in normal applications. For now, I would not enable them.

> **Session extension**
> Understood, if this isn't something that's supported we would either need to add it to the wrapper or disable it. I'm in favor of disabling until we have it functional andthen maybe re-evaluate.

Some of the more recent SQLite API additions are on the todo list of the _SQLitePCL.raw_ folks, but that todo list hasn't been updated for 2 years. I have no idea whether work is in progress to add support for those API additions.

> **User authentication extension**
> If it's rarely used sure. I'd be in favor of keeping it if it doesn't require any modifications - this is something I'd personally explore using with what I'm currently working on.

Actually, this extension also needs extra support in the wrapper to be useful. So, for now I wouldn't include it.

Additionally, you should know that support for this extension by the _SQLite_ core team is half-hearted. If the extension is enabled the SQLite code makes checks to prevent unauthorized users from accessing the database. However, the code of the extension has a known bug (that is fixed in _SQLite3 Multiple Ciphers_) that I reported on the SQLite forum long ago, but up to now a fix was not applied to the original source code.

Another thing one must take into consideration is that a database file that was created with enabled user authentication can easily be opened and modified by an application that uses a SQLite version not having this extension enabled.

That is, the usefulness of this extension seems to be limited. Therefore, I tend to not enable it.

**Comment by jammerxd** [comment]
Gotcha - sounds like we're on the same page then with what we want to have be enabled.

**Comment by utelle** [comment]
> Gotcha - sounds like we're on the same page then with what we want to have be enabled.

I will check the list of options I used for my first attempts. They should mostly conform already with the list given here, except for the double-quoted literals.

I already started to add support for _SQLite3 Multiple Ciphers_ to the actual _SQLitePCL.raw_ code base. However, the workflow of that repository expects the native binaries in the `master` branch, and as already said in a previous post the `cb` workflow puts the resulting binaries in a separate branch called `staging`. Most likely it is a simple git operation, but at the moment I have no idea how and when these binaries are transferred from the `staging` branch to the `master` branch, as I see no traces of such a git operation in the [original repository](https://github.com/ericsink/cb).

**Comment by utelle** [comment]
In the meantime I forked the repository [ericsink/SQLitePCL.raw](https://github.com/ericsink/SQLitePCL.raw) and tried to add support for _SQLite3 Multiple Ciphers_. 

Not very suprising the [first workflow run](https://github.com/utelle/SQLitePCL.raw/actions/runs/6457822551/job/17530212280) failed. One reason is that the files generated by the **cb** project are not (yet) visible in branch `master`. There may be other glitches, too.

**Comment by bricelam** [comment]
I would love to help with this. But we shouldn't start by forking SQLitePCL.raw. I can create a new project structure from scratch to get all the C#/.NET/NuGet parts going. Where will the native binaries come from? Are they already being built somewhere that we can just download from?

**Comment by jammerxd** [comment]
That would be awesome! We currently don't have the binaries available for download, but I can confirm they do build on windows, linux and osx (x86 and m1/m2) and could potentially zip them here if needed to get started.

**Comment by bricelam** [comment]
We should also decide which platforms we want to support. The list for the main SQLitePCLRaw bundles is quite extensive:

- browser-wasm (Emscripten)
- linux-arm
- linux-arm64
- linux-armel
- linux-mips64
- linux-musl-arm
- linux-musl-arm64
- linux-musl-x64
- linux-ppc64le
- linux-s390x
- linux-x64
- linux-x86
- maccatalyst-arm64
- maccatalyst-x64
- osx-arm64
- osx-x64
- win-arm
- win-arm64
- win-x64
- win-x86
- win10-arm (UWP)
- win10-arm64 (UWP)
- win10-x64 (UWP)
- win10-x86 (UWP)

**Comment by bricelam** [comment]
Forgot some:

- Apple TV
- iOS (including the simulator)
- Android (lots of variations)

**Comment by utelle** [comment]
> I would love to help with this.

That's really great!

> But we shouldn't start by forking SQLitePCL.raw.

I should have asked you first. 😄 

I already forked both, [ericsink/SQLitePCL.raw](https://github.com/ericsink/SQLitePCL.raw/) and [ericsink/cb](https://github.com/ericsink/cb/):

- [utelle/SQLitePCL.raw](https://github.com/utelle/SQLitePCL.raw/)
- [utelle/cb](https://github.com/utelle/cb).

I added support for _SQLite3 Multiple Ciphers_ in both repositories, see branch `sqlite3mc`. The **cb** workflow runs successfully already, with one exception **Windows ARM**.

> I can create a new project structure from scratch to get all the C#/.NET/NuGet parts going. Where will the native binaries come from? Are they already being built somewhere that we can just download from?

Yes, as said above I forked Eric's **cb** project. The binaries can be found in subdirectory [bld/bin/e_sqlite3mc](https://github.com/utelle/cb/tree/staging/bld/bin/e_sqlite3mc) of the [cb staging branch](https://github.com/utelle/cb/tree/staging).

> We should decide which platforms we want to support. The list for the main SQLitePCLRaw bundles is quite extensive:

Well, in principle we could support all platforms that are currently included in the **cb** project.

**Comment by utelle** [comment]
> We currently don't have the binaries available for download,

Fortunately, that's no longer true, because my fork of the **cb** repo already generates many binaries - although they should be tested that they actually work as expected.

> but I can confirm they do build on windows, linux and osx (x86 and m1/m2)

The **cb** project generates macOS binaries for _x86_64_ and _arm64_. We could check whether we are able to extend the procedure to generate binaries for _m1/m2_ as well.

**Comment by bricelam** [comment]
Oh wonderful! Ok, I'm a little more caught up now that I've read the entire thread. 😉 Using a `cb` fork to build all the binaries will work great.

> The workflow puts the resulting binaries in a separate branch called `staging`. At the moment I don't know how and when these binaries are transferred to the main branch.

I think this is currently a manual step. Once all the binaries are ready to flow into the SQLitePCL.raw repo, he merges from staging to master. Then kicks of a build over there which pulls master.

We probably don't need to commit anything to a branch. We can probably just have our other repo download the latest GitHub Actions artifacts directly.

**Comment by bricelam** [comment]
My comments on compile-time options:

> Disable support for double-quoted literals

Do it. This shouldn't affect any sane user, or any .NET library worth its salt that generates SQL.

These three enabled by SQLitePCLRaw are important the higher-level .NET library [EF Core](https://github.com/dotnet/efcore):

- SQLITE_ENABLE_COLUMN_METADATA
- SQLITE_ENABLE_JSON1
- SQLITE_ENABLE_MATH_FUNCTIONS

This one makes for a much better cross-database experience:

- SQLITE_DEFAULT_FOREIGN_KEYS

> File oriented extensions, Session extension, User authentication extension

Drop 'em.

> Useful extensions

I don't know what SQLITE_ENABLE_EXTFUNC is.

In EF Core, we've pushed users toward SpatiLite instead of SQLITE_ENABLE_GEOPOLY for now.

It's very easy to use .NET's implementation for SQLITE_ENABLE_REGEXP, SQLITE_ENABLE_SHA3, and SQLITE_ENABLE_UUID, so these really would just be adding size to the binary. I'd probably just disable them.

```cs
connection.CreateFunction("regexp", Regex.IsMatch);
```

As for SQLITE_ENABLE_SERIES and SQLITE_SOUNDEX, I haven't seen much use of them in .NET (especially since they're not enabled by SQLitePCLRaw), so unless they're useful in context of SQLite3MC, I'd probably just disable them.

**Comment by utelle** [comment]
> Using a `cb` fork to build all the binaries will work great.

I renamed the repo to [SQLite3MultipleCiphers-cb](https://github.com/utelle/SQLite3MultipleCiphers-cb) to make clear it is about _SQLite3 Multiple Ciphers_.

Currently, the the **cb** workflow builds binaries for all variants of SQLite:

- `sqlite3`, `e_sqlite3` - Original SQLite library
- `sqlcipher`, `e_sqlcipher` - Zetetic's SQLCipher library
- `e_sqlite3mc` - SQLite3 Multiple Ciphers

In my first attempt I chose the name `e_sqlite3mc` as the library name for the binaries - without knowing whether the `e_` prefix has a special meaning or not. However, just `sqlite3mc` seems to be more logical - unless there are reasons for the `e_` prefix.

> > The workflow puts the resulting binaries in a separate branch called `staging`. At the moment I don't know how and when these binaries are transferred to the main branch.
> 
> I think this is currently a manual step. Once all the binaries are ready to flow into the SQLitePCL.raw repo, he merges from staging to master. Then kicks off a build over there which pulls master.

Ok. However, in Eric's public **cb** repo I see no traces of such merge operations. So, that is a bit confusing.

> We probably don't need to commit anything to a branch. We can probably just have our other repo download the latest GitHub Actions artifacts directly.

That can be adjusted later on to the needs of the NuGet workflow.

**Comment by utelle** [comment]
> My comments on compile-time options:
> 
> > Disable support for double-quoted literals
> 
> Do it. This shouldn't affect any sane user, or any .NET library worth its salt that generates SQL.

Very good. I will keep the option `SQLITE_DQS=0` then.

> These three enabled by SQLitePCLRaw are important to the higher-level .NET library [EF Core](https://github.com/dotnet/efcore):
> 
> * SQLITE_ENABLE_COLUMN_METADATA
> * SQLITE_ENABLE_JSON1
> * SQLITE_ENABLE_MATH_FUNCTIONS

These options are in the basic set of options and are therefore already enabled.

> This one makes for a much better cross-database experience:
> 
> * SQLITE_DEFAULT_FOREIGN_KEYS

Same as above.

> > File oriented extensions, Session extension, User authentication extension
> 
> Drop 'em.

The source code contains those extensions, so it will be easy to enable them later, in case support for them is added in the .Net wrapper in the future.

> > Useful extensions
> 
> I don't know what SQLITE_ENABLE_EXTFUNC is.

This is an extension that provides many math and string UDFs for SQLite. It was created long before the SQLite developer team decided to add `SQLITE_ENABLE_MATH_FUNCTIONS`. In my own projects I frequently needed various math functions, and therefore this extension was part of [wxSQLite3](https://github.com/utelle/wxsqlite3) (and now [SQLite3 Multiple Ciphers](https://github.com/utelle/SQLite3MultipleCiphers)) for already a long time. [Here](https://github.com/utelle/SQLite3MultipleCiphers/issues/22) you find a comparison of both extensions.

Both extensions can be enabled at the same time. If `SQLITE_ENABLE_MATH_FUNCTIONS` is enabled the code for the corresponding functions in the EXTFUNC extension will be excluded from compilation.

> In EF Core, we've pushed users toward [SpatiLite](https://www.gaia-gis.it/fossil/libspatialite/index) instead of SQLITE_ENABLE_GEOPOLY for now.

Ok, I'll drop `SQLITE_ENABLE_GEOPOLY` for now.

> It's very easy to use .NET's implementation for SQLITE_ENABLE_REGEXP, SQLITE_ENABLE_SHA3, and SQLITE_ENABLE_UUID, so these really would just be adding size to the binary. I'd probably just disable them.

Ok, I will disable them.

> As for SQLITE_ENABLE_SERIES and SQLITE_SOUNDEX, I haven't seen much use of them in .NET (especially since they're not enabled by SQLitePCLRaw), so unless they're useful in context of SQLite3MC, I'd probably just disable them.

No, _SQLite3 Multiple Ciphers_ itself doesn't make use of those extensions. That is, they can be disabled.

In case there is a user demand for certain extensions in the future, they can be easily enabled again.

**Comment by utelle** [comment]
As mentioned in a prior post generating _SQLite3 Multiple Ciphers_ binaries failed for Windows ARM. 

In the meantime I analyzed why that happened. The reason was that the header file `windows.h` includes somewhere internally the header file `arm_neon.h`, so that later on in my own code this header file was not included anymore and a little necessary tweak by defining a certain symbol was not applied, leading to invalid Neon function declarations.

This has been fixed and now the binaries for **all** platforms and architectures can be build successfully.

**Comment by bricelam** [comment]
>> I don't know what SQLITE_ENABLE_EXTFUNC is.

> This is an extension that provides many math and string UDFs for SQLite.

Ah. Either way then. I'm sure it doesn't add much to the binary size.

**Comment by utelle** [comment]
> > > I don't know what SQLITE_ENABLE_EXTFUNC is.
> 
> > This is an extension that provides many math and string UDFs for SQLite.
> 
> Ah. Either way then. I'm sure it doesn't add much to the binary size.

Compared to the code of the encryption extension the size increase for the function extension is really neglectable.

For generating the binaries in [SQLite3MultipleCiphers-cb](https://github.com/utelle/SQLite3MultipleCiphers-cb/tree/sqlite3mc) the following default set of SQLite options is used (as defined in Eric Sink's repo):
```
SQLITE_ENABLE_COLUMN_METADATA
SQLITE_ENABLE_FTS3_PARENTHESIS
SQLITE_ENABLE_FTS4
SQLITE_ENABLE_FTS5
SQLITE_ENABLE_JSON1
SQLITE_ENABLE_MATH_FUNCTIONS
SQLITE_ENABLE_RTREE
SQLITE_ENABLE_SNAPSHOT
SQLITE_DEFAULT_FOREIGN_KEYS=1
```

and in addition the following options are used for the _SQLite3 Multiple Ciphers_ variant:
```
CODEC_TYPE=CODEC_TYPE_CHACHA20   // Default cipher scheme
SQLITE_TEMP_STORE=2              // Temporary storage in memory
SQLITE_USE_URI=1                 // Support config parameters via URI parameters
SQLITE_DQS=0                     // Do NOT support double-quoted literals
SQLITE_SECURE_DELETE=1           // Use secure delete
SQLITE_ENABLE_EXTFUNC=1          // Enable function extension
```

**Comment by utelle** [comment]
> Create a nuget packge that implements the SQLitePCLRaw provider as a bundle so that c# applications can use SQLite3MultipleCiphers.

In teamwork with @bricelam and @ericsink building a [SQLite3 Multiple Ciphers NuGet package](https://www.nuget.org/packages/SQLitePCLRaw.bundle_e_sqlite3mc) has been made a part of the main [SQLitePCLRaw](https://github.com/ericsink/SQLitePCL.raw) project. A first prerelease as NuGet package [SQLitePCLRaw.bundle_e_sqlite3mc](https://www.nuget.org/packages/SQLitePCLRaw.bundle_e_sqlite3mc) has been made yesterday. Please give it a try (and report any issues you experience).
