### ISSUE TITLE
Add a link from the "Installation" documentation page to the release files on GitHub

### ISSUE THREAD

**Issue by emkey08** [utelle/SQLite3MultipleCiphers#122]
Please add a prominent link from the [Installation](https://utelle.github.io/SQLite3MultipleCiphers/docs/installation/install_overview/) documentation page to the [Release files on GitHub](https://github.com/utelle/SQLite3MultipleCiphers/releases) so that users can easily find the download of the pre-built binary packages.

Thank you very much!

**Comment by utelle** [comment]
Done.
