### ISSUE TITLE
Estimated date for a first release ?

### ISSUE THREAD

**Issue by Willena** [utelle/SQLite3MultipleCiphers#13]
Hi @utelle,

Can we consider the codebase is stable ? 
Will you release a version in the next weeks or months ? 
Are there any known blocking issues ? 

Thanks

**Comment by utelle** [comment]
> Can we consider the codebase is stable ?

Well, it is stabilizing, I'd say. I did some code cleanup recently and fixed a few issues.

> Will you release a version in the next weeks or months?

The official release of **SQLite 3.33.0** is due within the next couple of weeks (see [SQLite draft website](https://www.sqlite.org/draft/releaselog/3_33_0.html)). I intend to make a first release of **SQLite3 Multiple Ciphers** shortly thereafter - that is, most likely within August 2020.

> Are there any known blocking issues?

Not that I know of. However, I haven't got much feedback within the last couple of months.

**Comment by Willena** [comment]
@utelle Thank you for the information and your quick answer. I'll patiently wait for the 3.33.0 release.
