### ISSUE TITLE
Feature Request: Add support for algorithms from `liboqs` (Quantum Safe)

### ISSUE THREAD

**Issue by titanism** [utelle/SQLite3MultipleCiphers#136]
See <https://github.com/open-quantum-safe/liboqs#supported-algorithms> for documentation and <https://github.com/open-quantum-safe/liboqs-rust> for example binding (albeit in Rust).

**Comment by utelle** [comment]
Adding support for _Kyber-1024_ (offering security roughly equivalent to _AES-256_) is already under investigation. Currently, _Kyber_ is the only algorithm relevant in this context that is (or will be) standardized. However, it is not decided yet whether it will actually be added to this project and - if yes - when this will happen.

Symmetric encryption, especifically _AES-256_ is believed to be quantum-resistant. That is, quantum computers are not expected to be able to reduce the attack time enough to be effective if the key sizes are large enough. In case that information will be published invalidating this assumption, the priority to add support for post-quantum algorithms will be increased, of course.

**Comment by utelle** [comment]
Just as a side note: **all** (key encapsulation) algorithms offered by [liboqs](https://github.com/open-quantum-safe/liboqs#supported-algorithms) are **asymmetric** algorithms. For _SQLite3 Multiple Ciphers_ we need **symmetric** algorithms. So, none of the _liboqs_ algorithms can be used directly.

**Comment by utelle** [comment]
After doing some further research we come to the following conclusion:

**Symmetric** encryption algorithms are believed to be _quantum resistant_, as long as the key size is sufficiently large. _SQLite3 Multiple Ciphers_ already offers support for 2 well-known algorithms with 256-bit keys: **AES-256** and **ChaCha20**.

Adding support for **asymmetric** encryption algorithms doesn't make much sense in the context of SQLite database encryption, because **asymmetric** encryption requires very long keys and can not be performed as efficiently as **symmetric** encryption. Therefore this issue will be closed for now as _not planned_.

**Comment by utelle** [comment]
> @utelle can you please share your research and references to support this statement?
> 
> > Symmetric encryption algorithms are believed to be quantum resistant

First hints can be found in the Wikipedia article about [Post-Quantum Cryptography](https://en.wikipedia.org/wiki/Post-quantum_cryptography) (see 3rd paragraph in 1st section). This article contains references to various sources. 

However, you can easily find further references by looking for articles about _quantum-resistant cryptography_. For example

- [Quantum-Resistant Cryptography](https://arxiv.org/abs/2112.00399) by John Preuß Mattsson, Ben Smeets, Erik Thormarker
- [The Impact of Quantum Computing on Present Cryptography](https://arxiv.org/abs/1804.00200) by Vasileios Mavroeidis, Kamer Vishi, Mateusz D. Zych, Audun Jøsang

just to name a few.

Adding support for new quantum-resistant algorithms will be reconsidered, as soon as it is proven that current **symmetric** algorithms are not quantum-safe. I'm pretty sure that new quantum-resistant symmetric algorithms will be developed in this case.
