### ISSUE TITLE
Removal of user authentication extension

### ISSUE THREAD

**Issue by utelle** [utelle/SQLite3MultipleCiphers#138]
According to [this post on the SQLite forum](https://sqlite.org/forum/forumpost/db235b3070) the _User Authentication Extension_ has been formally deprecated (see also [SQLite Check-In message](https://www.sqlite.org/src/info/249048b0cbc37058) or deprecation notice in file [user-auth.txt](https://www.sqlite.org/src/file?name=ext/userauth/user-auth.txt&ci=trunk)).

Therefore I intend to remove the _User Authentication Extension_ from the _SQLite3 Multiple Ciphers_ code base for the next release.

If someone has strong arguments to keep this extension in the _SQLite3 Multiple Ciphers_ code base, please drop a note here.

**Comment by utelle** [comment]
No feedback is also a kind of feedback.

For the version of _SQLite3 Multiple Ciphers_ based on _SQLite 3.46.0_ (expected in July 2024) the source code of the user authentication extension will be removed from the code base.

**Comment by topmin** [comment]
Good!

**Comment by rogerbinns** [comment]
SQLite [just removed it too](https://www.sqlite.org/src/info/3a3f7bf4307c27e56546e51da06ecc9a262cdf155fda2dd359aa2326d207a147)

**Comment by utelle** [comment]
@rogerbinns Thanks for reminding me. I will remove it, too, now that this extension is _officially_ gone. Actually, this will happen, when _SQLite 3.48.0_ will be released. Version 3.47.0 still includes it, and I expect that versions 3.47.x (if they happen) will also include it.

**Comment by utelle** [comment]
The _User Authentication extension_ was finally removed for [release 2.0.0](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v2.0.0). 

The release of _SQLite version 3.48.0_ is expected mid of January 2025 according to the [current schedule](https://www.sqlite.org/draft/releaselog/3_48_0.html).
