### ISSUE TITLE
Problem connecting a database using SQLite Studio v3.4.0

### ISSUE THREAD

**Issue by rossanoparis** [utelle/SQLite3MultipleCiphers#139]
Hallo at all

I'm using SQLite3 Multiple Ciphers v1.8.2 which I built from its source code.
I'm able to create an encrypted database file using this uri: `uri=file:encrypt-02.db?mode=rwc&cache=private`
To specify the encryption mode I use PRAGMAs in this way:
```
PRAGMA key = 'mypassphrase'
PRAGMA cipher = 'aes256cbc'
```

Everythings works fine, I'm able to create tables and so on ...
My problem arise when I want to connect such database in SQLite Studio v3.4.0

I get the following error
![image](https://github.com/utelle/SQLite3MultipleCiphers/assets/33904565/3624419b-531c-4c54-8a44-a31faacd5a3e)

Am I doing something not allowed?
Should I specify something in "Cipher configuration"?

**Comment by utelle** [comment]
> I'm using SQLite3 Multiple Ciphers v1.8.2 which I built from its source code. I'm able to create an encrypted database file using this uri: `uri=file:encrypt-02.db?mode=rwc&cache=private` To specify the encryption mode I use PRAGMAs in this way:
> 
> ```
> PRAGMA key = 'mypassphrase'
> PRAGMA cipher = 'aes256cbc'
> ```

Is this the **exact order** in which you performed the `PRAGMA` statements?

> Everythings works fine, I'm able to create tables and so on ... My problem arise when I want to connect such database in SQLite Studio v3.4.0

 If the answer to my above question is **yes**, it is not surprising that you couldn't open the database in _SQLite Studio_.

The **order** of `PRAGMA` statements _**matters**_! If `PRAGMA key` is executed **first** the library will use the _default_ cipher scheme - that is, _ChaCha20-Poly1305_ unless you changed the default when compiling the library.

Executing `PRAGMA cipher` as the **second** statement will have no effect.

> Am I doing something not allowed?

No. Just change the order of `PRAGMA` statements on creating the database to 

```SQL
PRAGMA cipher = 'aes256cbc'
PRAGMA key = 'mypassphrase'
```

Alternatively, you could specify `cipher=aes256cbc` as an URI parameter.

> Should I specify something in "Cipher configuration"?

No, at least not for the cipher scheme `aes256cbc`.

**Comment by rossanoparis** [comment]
Thank you @utelle, you are right of course.
My problem was due to PRAGMA execution order, which it must be like this
```
PRAGMA cipher = 'aes256cbc'
PRAGMA key = 'mypassphrase'
```
