### ISSUE TITLE
How to use Quicklz to compress databases?

### ISSUE THREAD

**Issue by topmin** [utelle/SQLite3MultipleCiphers#143]
What should I do if I don't use ZLIB and instead use Quicklz?
Thank you.

**Comment by Qriist** [comment]
> What should I do if I don't use ZLIB and instead use Quicklz? Thank you.

You can build against MINIZ (which is included in SQL3MC's build files).

Set the following preprocessor symbols to enable all compression related features:

- SQLITE3MC_USE_MINIZ=1
- SQLITE_ENABLE_COMPRESS=1 
- SQLITE_ENABLE_SQLAR=1
- SQLITE_ENABLE_ZIPFILE=1

More complete information can be found on the documentation page here:
https://utelle.github.io/SQLite3MultipleCiphers/docs/installation/install_overview/#optional-features

**Comment by topmin** [comment]
Thank you, SQLite3MultipleCiphers is indeed a great project!

**Comment by utelle** [comment]
I assume the problem is solved. Reopen the issue if necessary.
