### ISSUE TITLE
When `#define SQLITE_ENABLE_CSV 1` `struct DIRENT` will report an error

### ISSUE THREAD

**Issue by topmin** [utelle/SQLite3MultipleCiphers#144]
When `#define SQLITE_ENABLE_CSV 1`
Line 289772: `typedef struct DIRENT DIRENT;` should be changed to `typedef struct _DIRENT DIRENT;`
Line 289774: `struct DIRENT {` should be changed to struct _DIRENT {
Otherwise, if two DIRENTs have the same name, the compiler will report an error.

**Comment by utelle** [comment]
> When `#define SQLITE_ENABLE_CSV 1`
> Line 289772: `typedef struct DIRENT DIRENT;` should be changed to `typedef struct _DIRENT DIRENT;`
> Line 289774: `struct DIRENT {` should be changed to struct _DIRENT {
> Otherwise, if two DIRENTs have the same name, the compiler will report an error.

The CSV extension doesn't make use of this `struct`. That is, using  `#define SQLITE_ENABLE_CSV 1` should not impose a problem.

However, using `#define SQLITE_ENABLE_FILEIO 1` leads to the problem you describe. That is, don't use this symbol to avoid the problem.

The code in question comes from the source file `test_windirent.h` which is part of the original SQLite distribution. The compilers _Visual C++_  and _GCC_ don't have problems to compile this code flawlessly. However, the compiler _bcc32c_ used by you is not able to compile the code.

If you want this issue fixed please report it on the [SQLite forum](https://sqlite.org/forum) and ask for a code change. If you are lucky, the next SQLite release will then contain a fix.

If you want to enable the _file IO extension_ without waiting for an official fix, you can probably work around the problem by adding the following code at the beginning of the source code:

```C
#ifndef DIRENT_DEFINED
#define DIRENT_DEFINED
typedef struct _DIRENT DIRENT;
typedef DIRENT *LPDIRENT;
struct _DIRENT {
  ino_t d_ino;               /* Sequence number, do not use. */
  unsigned d_attributes;     /* Win32 file attributes. */
  char d_name[NAME_MAX + 1]; /* Name within the directory. */
};
#endif
```
I haven't tested this workaround, though. Good luck!

**Comment by utelle** [comment]
The problem has to be fixed upstream.

**Comment by topmin** [comment]
Thank you. The issue has been resolved by changing struct DERENT to struct _DERENT.
