### ISSUE TITLE
Typo in SQLite version in readme.md

### ISSUE THREAD

**Issue by mxdamien** [utelle/SQLite3MultipleCiphers#151]
Hello !

It seems like there is small typo in readme.md regarding the SQLite Version. According to the commit history and the version in sqlite3.h SQLite3MultipleCiphers 1.8.4 is based on SQLite 3.4.2. The Readme states SQLite 3.45.5, which is not yet released.

https://github.com/utelle/SQLite3MultipleCiphers/blob/80722b01faeb96328579c5cd594a722240040c7f/src/sqlite3.h#L149

https://github.com/utelle/SQLite3MultipleCiphers/blob/80722b01faeb96328579c5cd594a722240040c7f/readme.md?plain=1#L14

Best regards,

David

**Comment by utelle** [comment]
Version 1.8.5 (based on SQLite 3.46.0) was released today. Version infos should now be correct - unless I introduced new typos. 😉
