### ISSUE TITLE
pragma hexkey is not documented

### ISSUE THREAD

**Issue by rogerbinns** [utelle/SQLite3MultipleCiphers#154]
The [pragma documentation](https://utelle.github.io/SQLite3MultipleCiphers/docs/configuration/config_sql_pragmas/) does not mention `pragma hexkey`.

The relevance is that [SQLite doesn't accept blobs in pragmas](https://github.com/rogerbinns/apsw/issues/523) so `hexkey` is way easier to use, and what is documented in [apsw-sqlite3mc](https://github.com/utelle/apsw-sqlite3mc/tree/sqlite3mc?tab=readme-ov-file#usage).  I found it in the pragma in the SEE documentation.

**Comment by utelle** [comment]
Thanks for reporting this documentation issue. I will adjust the documentation.

**Comment by utelle** [comment]
Documentation was adjusted.
