### ISSUE TITLE
Some windows only functions defined incorrectly

### ISSUE THREAD

**Issue by rogerbinns** [utelle/SQLite3MultipleCiphers#155]
Using the amalgamation around line 116 there is a block like this with several functions.

````
/* SQLite functions only needed on Win32 */
extern SQLITE_API void sqlite3_win32_write_debug(const char*, int);
extern SQLITE_API char *sqlite3_win32_unicode_to_utf8(LPCWSTR);
extern SQLITE_API char *sqlite3_win32_mbcs_to_utf8(const char*);
````

They are forcibly defined as extern and as SQLITE_API.  That causes conflicts when I define SQLITE_API to be static.  They should only be defined SQLITE_API which defaults to extern anyway.

The functions also aren't mentioned in the documentation, so they should either be documented, removed, or made private.

FWIW the amalgamation also has a random smattering of \r\n instead of \n in places which IDEs automagically convert to \n causing diff issues.

**Comment by utelle** [comment]
> Using the amalgamation around line 116 there is a block like this with several functions.
> 
> ```
> /* SQLite functions only needed on Win32 */
> extern SQLITE_API void sqlite3_win32_write_debug(const char*, int);
> extern SQLITE_API char *sqlite3_win32_unicode_to_utf8(LPCWSTR);
> extern SQLITE_API char *sqlite3_win32_mbcs_to_utf8(const char*);
> ```
> 
> They are forcibly defined as extern and as SQLITE_API. That causes conflicts when I define SQLITE_API to be static. They should only be defined SQLITE_API which defaults to extern anyway.

AFAICT the `extern` keyword can be removed. And I will do so.

> The functions also aren't mentioned in the documentation, so they should either be documented, removed, or made private.

These function are part of SQLite itself. Yes, they are not documented, but at least in the Windows DLLs that can be downloaded from the SQLite website they are exported.

> FWIW the amalgamation also has a random smattering of \r\n instead of \n in places which IDEs automagically convert to \n causing diff issues.

I will have to check which source files have differing line endings. I'll try to fix this for the next release.

**Comment by rogerbinns** [comment]
The win32 functions don't appear in sqlite3.h but are in the sqlite3.c amalgamation.  They are delcared SQLITE_API but not extern.

It looks like they are used by shell.c so best guess is a sort of private interface between the shell and the amalgamation and means the shell doesn't have to re-implement them.  It also explains why they are undocumented.

**Comment by utelle** [comment]
I removed the `extern` keyword in commit 41b3c6d199ee0825127a0bd508f485fc29c27a5a.

**Comment by utelle** [comment]
> FWIW the amalgamation also has a random smattering of \r\n instead of \n in places which IDEs automagically convert to \n causing diff issues.

AFAICT **all** line endings in the amalgamation are `\r\n`. The amalgamation is generated by a Python script (which is located in the `scripts` subdirectory) - executed on a Windows machine.

**Comment by rogerbinns** [comment]
It is hard to tell exactly what is going on with the end of lines.  To reproduce open the file in vscode, add a space or anything else harmless and then save the file.  I get a git diff like the following.  It may actually be adding \r back in the lines that end in \n only.

![image](https://github.com/utelle/SQLite3MultipleCiphers/assets/553885/cc35cd3b-656a-436b-bc71-c5f1cf8e7afa)

**Comment by utelle** [comment]
> It is hard to tell exactly what is going on with the end of lines. To reproduce open the file in vscode, add a space or anything else harmless and then save the file. I get a git diff like the following. It may actually be adding \r back in the lines that end in \n only.

I think I found the cause. The differing lines have trailing blanks in the original amalgamation. I will check whether those trailing blanks are already in the original source files. And if so, I will clean up the sources.

**Comment by utelle** [comment]
I cleaned up the trailing white space and updated the amalgamation in [apsw-sqlite3mc](https://github.com/utelle/apsw-sqlite3mc).

**Comment by rogerbinns** [comment]
Note there are still some end of line issues in the amalgamation in apsw-sqlite3mc.

Open the file with vcscode, add a blank line, and save.  You get a diff like the screen shot above.

**Comment by utelle** [comment]
> Note there are still some end of line issues in the amalgamation in apsw-sqlite3mc.

Most likely the problem is that the file stored in the GitHub repository contains CRLF line endings. In my other repositories I have a `.gitattributes` file, so that line endings are normalized automatically.

I committed a file version with Unix LF line endings. Check whether you still see end of line issues.

And I added a `.gitattributes` file.

**Comment by rogerbinns** [comment]
There are still trailing whitespace issues.  vscode is set to remove trailing whitespace and is still finding it.

Look for the line with `{` after `typedef struct _Rijndael` to see an example.

**Comment by utelle** [comment]
Should now be fixed.
