### ISSUE TITLE
ascon128 misaligned load

### ISSUE THREAD

**Issue by rogerbinns** [utelle/SQLite3MultipleCiphers#162]
Use a sanitizer.

````
import apsw

con = apsw.Connection("testdb")
print(f"{con.pragma("cipher", "ascon128")=}")
print(f"{con.pragma("key", "hello")=}")
con.execute("create table x(y); insert into x values(randomblob(32768))")
````

Results

````
con.pragma("cipher", "ascon128")='ascon128'
con.pragma("key", "hello")='ok'
/space/mc/sqlite3/sqlite3.c:280144:16: runtime error: load of misaligned address 0x53100005184c for type 'uint64_t', which requires 8 byte alignment
0x53100005184c: note: pointer points here
  00 00 00 00 ef ed 7a 53  7b 6d 43 a3 f2 a4 9c 75  4f 91 56 27 00 00 00 00  00 00 00 00 00 00 00 00
              ^ 
````

The alignment error is reported ~16 times for ~3 different addresses

**Comment by utelle** [comment]
> ```
> /space/mc/sqlite3/sqlite3.c:280144:16: runtime error: load of misaligned address 0x53100005184c for type 'uint64_t', which requires 8 byte alignment
> ```
> 
> The alignment error is reported ~16 times for ~3 different addresses

For the implementation of the _Ascon_ algorithms I use mostly the code from the [Ascon repository](https://github.com/ascon/ascon-c). I just checked the repository and found out that the alignment issue was addressed in April 2024.

I will adjust SQLite3MC's _Ascon_ code.

**Comment by utelle** [comment]
I applied the necessary modifications. The issue should now be fixed.
