### ISSUE TITLE
JS Wasm - Setting key failed. Encryption is not supported by the VFS

### ISSUE THREAD

**Issue by sozoo-k5u** [utelle/SQLite3MultipleCiphers#176]
Thank you very much for the good library. 
From this article https://www.bricelam.net/2023/11/10/more-sqlite-encryption.html , I have used the .NET package and created an encrypted database with Chacha20. I can also open this database using Sqlite Studio, so far so good.

Unfortunately, when I download this database from the server and store it in OPFS, I cannot open it with JS wasm

Here is the code I use to connect with the database
```
await sqlClient('open', {
			filename: `file:${dbName}?vfs=opfs`,
			persistent: true,
			key: 'xxxxxxxx',
		}); 
```

or via SQL:
 
```		
PRAGMA key=xxxxxxxx
```

Here is the error I am getting: 
 
```
SQLITE_ERROR: sqlite3 result code 1: Setting key failed. Encryption is not supported by the VFS..
``` 

Could you please provide me an example code to connect with an encrypted database that is stored in OPFS?
Regards

**Comment by utelle** [comment]
> Unfortunately, when I download this database from the server and store it in OPFS, I cannot open it with JS wasm
> 
> Here is the code I use to connect with the database
> 
> ```
> await sqlClient('open', {
> 			filename: `file:${dbName}?vfs=opfs`,
> 			persistent: true,
> 			key: 'xxxxxxxx',
> 		}); 
> ```

In your code you request a pure OPFS VFS, and that's what you get: OPFS _without_ encryption support.

You have to tell SQLite that you want to use a VFS with encryption support. To get encryption support, you have to prefix the VFS name with `multipleciphers-` resulting in `multipleciphers-opfs`. That is, the following should work:

```
await sqlClient('open', {
			filename: `file:${dbName}?vfs=multipleciphers-opfs`,
			persistent: true,
			key: 'xxxxxxxx',
		}); 
```

**Comment by sozoo-k5u** [comment]
@utelle  Thank you for your quick response.
I have tried and it is working now with the main thread. You are a superstar.  
====================================================================
I also have a web worker that connects to the encrypted database in OPFS and is getting the same issue.
Can you please have a look and let me know what is wrong with it?
```
this.opfsWorkerDb = new this.sqlite3.oo1.OpfsDb({
			filename: 'encrypted_database.db',
			key: 'XXXXXXXX',
		});
```

**Comment by utelle** [comment]
> I have tried and it is working now with the main thread.

Good to hear.

> I also have a web worker that connects to the encrypted database in OPFS and is getting the same issue. Can you please have a look and let me know what is wrong with it?
> 
> ```
> this.opfsWorkerDb = new this.sqlite3.oo1.OpfsDb({
> 			filename: 'encrypted_database.db',
> 			key: 'XXXXXXXX',
> 		});
> ```

Well, how should SQLite know which VFS to use?

Again, specifying the VFS to be used should solve the issue.

> ```
> this.opfsWorkerDb = new this.sqlite3.oo1.OpfsDb({
> 			filename: 'encrypted_database.db?vfs=multipleciphers-opfs',
> 			key: 'XXXXXXXX',
> 		});
> ```

An alternative would be to make the VFS `multipleciphers-opfs` the **default** VFS. Then you don't need to specify the VFS anymore. This can be achieved by calling a C API function of SQLite3MC at the beginning of your application:

```
capi.sqlite3mc_vfs_create('opfs', 1)
```
This function creates the VFS `multipleciphers-opfs` (based on the _real_ VFS `opfs` - 1st parameter) and makes it the default VFS (`1` - 2nd parameter). This function returns an error code. If the return value is `0`, then all went ok.

**Comment by sozoo-k5u** [comment]
I did try with the filename: `encrypted_database.db?vfs=multipleciphers-opfs` but it did not work as expected. 
Running `capi.sqlite3mc_vfs_create('opfs', 1)` returns 12 but no luck at all.

I will try to prepare a full sample code for it then you can check further.

**Comment by utelle** [comment]
The return code 12 means `SQLITE_NOT_FOUND`. That is, the OPFS VFS was not found, when the function was invoked.

AFAIK OPFS has some restrictions. Does it work in a web worker, if you use an unencrypted database?

**Comment by sozoo-k5u** [comment]
Yes mate, it normally works in web worker (OPFS) with the unencrypted database.

**Comment by utelle** [comment]
> I did try with the filename: `encrypted_database.db?vfs=multipleciphers-opfs` but it did not work as expected.

If you specified the database file name exactly as given above, this may explain the problem - it is not a valid URI file name. Sorry for being a bit careless. For a valid URI file name it is necessary to add the prefix `file://`. Please try:

```
this.opfsWorkerDb = new this.sqlite3.oo1.OpfsDb({
			filename: 'file://encrypted_database.db?vfs=multipleciphers-opfs',
			key: 'XXXXXXXX',
		});
```

> Yes mate, it normally works in web worker (OPFS) with the unencrypted database.

Please call the C API function `capi.sqlite3_vfs_find('opfs')` immediately before you execute the above code. It should return a not-Null value, if the OPFS VFS was found - as it should, because you wrote that the code worked for an unencrypted database.

> I will try to prepare a full sample code for it then you can check further.

Unfortunately, JS WASM is **not** my programming domain. I do my best to generate the SQLite WASM build for _SQLite3 Multiple Ciphers_ and I perform the tests coming with _SQLite WASM_, but that's it.

**Comment by utelle** [comment]
Sorry for the delay. However, in the meantime I experimented with the samples coming with SQLite3 WASM. I modified the sample "demo-123-worker" to open the database using the VFS `multipleciphers-opfs`. The relevant code is

```
const capi = sqlite3.capi/*C-style API*/,
          oo = sqlite3.oo1/*high-level OO API*/;
const db = new oo.DB("/mydb.sqlite3",'ct', 'multipleciphers-opfs');
```
As you can see the code doesn't make use of the function `OpfsDb`. I suspect that `OpfsDb` uses a fixed VFS internally.

**Comment by sozoo-k5u** [comment]
Thank you so much. I can connect to the database using this format :
 ```
 'file://encrypted_database.db?vfs=multipleciphers-opfs'
 ```

 I now have an issue while using `PRAGMA key` for example with this code
```
PRAGMA key = 12345678;
SELECT * from products
``` 

it only returns [ok] that I guess for the 1st command only.
How could I use C-style API? As I am using chacha20 as default, what parameters I need to pass into this function 
 `sql3.capi.sqlite3_key() `

**Comment by sozoo-k5u** [comment]
never mind. I can connect right now. thank you so much for all your help

**Comment by utelle** [comment]
> I now have an issue while using `PRAGMA key` for example with this code
> 
> ```
> PRAGMA key = 12345678;
> SELECT * from products
> ```
> 
> it only returns [ok] that I guess for the 1st command only.

`PRAGMA key` returns the string `OK`, if no error occurred on setting up the encryption parameters. However, it does **not** confirm that the password given was correct. If the password was not correct, you will receive an error _"Not a database"_ on the first access to the database data.

> How could I use C-style API? As I am using chacha20 as default, what parameters I need to pass into this function `sql3.capi.sqlite3_key() `

The signature of `sqlite3_key` is `int sqlite3_key(sqlite3* dbHandle, string key, int keyLength);`.

**Comment by sozoo-k5u** [comment]
you can close the ticket now @utelle  Thank you very much
