### ISSUE TITLE
A question about licensing

### ISSUE THREAD

**Issue by ethindp** [utelle/SQLite3MultipleCiphers#178]
As it currently stands, this project is under the MIT license whereas the actual SQLite source code is licensed in the public domain. Would it be possible to re-license this project? I obviously would still give attribution but at least then this project would respect SQLite's original license terms. If re-licensing isn't possible, then I'd like the ambiguity in the MIT license to be cleared up, because I'm not certain whether I should put attribution in source code, in the binary, or both.

**Comment by utelle** [comment]
> As it currently stands, this project is under the MIT license whereas the actual SQLite source code is licensed in the public domain.

Correct. The MIT license applies to the parts I developed myself as well as the overall compilation. Included are some unmodified source files which are in the public domain, and will stay in the public domain if used stand-alone.

> Would it be possible to re-license this project?

No. Especially commercial users frequently ask for a "proper" license. The MIT license is a very liberal license. You can do with the code almost anything you like, except for claiming that you wrote the code yourself.

> I obviously would still give attribution but at least then this project would respect SQLite's original license terms.

_Public domain_ is **not** a license. Quote from the SQLite website: _"SQLite is in the public domain and does not require a license."_ That is, there are no SQLite license terms.

> If re-licensing isn't possible, then I'd like the ambiguity in the MIT license to be cleared up, because I'm not certain whether I should put attribution in source code, in the binary, or both.

In the MIT license it reads: _"The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software."_ What exactly is _ambiguous_?

**Comment by ethindp** [comment]
The ambiguous line is the line you quoted. Specifically, what counts as "software"? Is it the original source code form? Is it the compiled binary? Is it all possible forms that can be represented (in this case, source code and binary)? From the research that others on the project I'm incorporating this into (and that the lead has done) this line is particularly contentious, hence me raising this issue. Other licenses such as Zlib do not suffer this problem and are equally as sensible:

> This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.
Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:
> 1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required. 
> 2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software. 
> 3. This notice may not be removed or altered from any source distribution. 

However, since re-licensing is not possible (and I understand your reasong, I didn't know that commercial users wanted a "proper" license... Good to know), I thought I would ask just to make extra sure about disambiguating that particular line. I know a lot of people believe that that line means binary attribution, but I thought it would be best to consult with you instead of assuming.

**Comment by utelle** [comment]
> The ambiguous line is the line you quoted. Specifically, what counts as "software"? Is it the original source code form? Is it the compiled binary? Is it all possible forms that can be represented (in this case, source code and binary)?

It is whatever you distribute to your users, customers etc. In any case you should add the license file (possibly renaming it to something lke `SQLite3MC-LICENSE`) to your distribution. And typically the _About_ dialog or the help document of an application mentions the components that were used for implementing it, but the MIT license does not require this. However, it is good style.

> From the research that others on the project I'm incorporating this into (and that the lead has done) this line is particularly contentious, hence me raising this issue. Other licenses such as Zlib do not suffer this problem and are equally as sensible:

Zlib license and MIT license are very similar. However, the Zlib requires you to keep the license intact only with the sources, not with binaries. This is different for the MIT license, where binary distributions have to include the license, too.

> However, since re-licensing is not possible (and I understand your reasong, I didn't know that commercial users wanted a "proper" license... Good to know),

The legal situation is different in different countries. In Germany - where I live - commercial users often have "problems" with public domain software. Therefore the SQLite team offers for such users ["to buy a license"](https://www.sqlite.org/purchase/license) - see also [SQLite Copyright](https://sqlite.org/copyright.html).

> I thought I would ask just to make extra sure about disambiguating that particular line. I know a lot of people believe that that line means binary attribution, but I thought it would be best to consult with you instead of assuming.

The MIT license requires that a distribution containing the software (here: _SQLite3 Multiple Ciphers_) in any form (source or binary) shall include the license file. This could also be a copy of the license text in the documentation of your application.
