### ISSUE TITLE
Registering new ciphers

### ISSUE THREAD

**Issue by ethindp** [utelle/SQLite3MultipleCiphers#179]
So I don't know if I'm doing something wrong or if I'm encountering a bug. I'm trying to register a new cipher like so:

```cpp
static char XCHACHA20_CIPHER_NAME[] = "xchacha20poly1305";
static const CipherDescriptor XChaCha20Descriptor = {
	XCHACHA20_CIPHER_NAME,
	&alloc_cipher,
	&free_cipher,
	&clone_cipher,
	&cipher_get_legacy,
	&get_page_size,
	&get_reserved_size,
	&get_salt,
	&generate_key,
	&encrypt_page,
	&decrypt_page
};
static const CipherParams XChaCha20Params[] = {
	{nullptr, 0, 0, 0, 0},
};
```

(This uses my project's crypto library for the project I'm working on, hence the cipher for uniformity.) However, whether I put the `&` before the functions or not, I still get `SQLITE_ERROR` when calling `sqlite3mc_register_cipher`. All of the functions match the function signatures and from what I can tell I'm doing everything right according to how other ciphers are registered, but if this isn't a bug, am I doing something I shouldn't be doing?

**Comment by utelle** [comment]
> So I don't know if I'm doing something wrong or if I'm encountering a bug.

Yes and yes. It's a bug in your code.

> I'm trying to register a new cipher like so:
> 
> ```c++
> static char XCHACHA20_CIPHER_NAME[] = "xchacha20poly1305";
> static const CipherDescriptor XChaCha20Descriptor = {
> 	XCHACHA20_CIPHER_NAME,
> 	&alloc_cipher,
> 	&free_cipher,
> 	&clone_cipher,
> 	&cipher_get_legacy,
> 	&get_page_size,
> 	&get_reserved_size,
> 	&get_salt,
> 	&generate_key,
> 	&encrypt_page,
> 	&decrypt_page
> };
> ```

This should work, but using ampersands (`&`) here is not necessary, but does no harm either.

Have you ever inspected a single cipher scheme implementation of _SQLite3 Multiple Ciphers_? You should. It could make your life easier.

> ```c++
> static const CipherParams XChaCha20Params[] = {
> 	{nullptr, 0, 0, 0, 0},
> };
> ```

This is wrong.

Again: Have you ever inspected a single cipher scheme implementation of _SQLite3 Multiple Ciphers_? You should. Really.

Read the code and try to understand what's going on. Or do it in the same way as it is done there.

> [...] and from what I can tell I'm doing everything right according to how other ciphers are registered, but if this isn't a bug,

I can assure you that it isn't a bug in _SQLite3 Multiple Ciphers_.

> am I doing something I shouldn't be doing?

Yes.

**Comment by ethindp** [comment]
> Have you ever inspected a single cipher scheme implementation of SQLite3 Multiple Ciphers? You should. It could make your life easier.

Yes, I have. Several times, in fact.

> This is wrong.
>
> Again: Have you ever inspected a single cipher scheme implementation of SQLite3 Multiple Ciphers? You should. Really.
>
> Read the code and try to understand what's going on. Or do it in the same way as it is done there.

There's no need to be condescending about it. Regardless, I have indeed tried to do exactly what is done internally, but for whatever reason, if I do:

```cpp
static const CipherParams XChaCha20Params[] = {
	{"", 0, 0, 0, 0},
};
```

My compiler complains and says it can't cast `const char[1]` to `char*`. So using `nullptr` was the only way I could think of to fix that problem. It's the same reason I do the name string explicitly: the struct takes a `char*` as the cipher name, which means you can't use string literals, in C++ anyway. In the C code you use macros and somehow this is able to get around that particular problem (or maybe it's compiling it in C mode).

**Comment by utelle** [comment]
> Regardless, I have indeed tried to do exactly what is done internally,

Using `nullptr` instead of an empty string `""` is **not** exactly the same as done in the cipher implementations. There the macro `CIPHER_PARAMS_SENTINEL` is used to mark the end of the list of configuration parameters. And the macro uses an empty string for the parameter name, not a `nullptr`.

> but for whatever reason, if I do:
> 
> ```c++
> static const CipherParams XChaCha20Params[] = {
> 	{"", 0, 0, 0, 0},
> };
> ```
> 
> My compiler complains and says it can't cast `const char[1]` to `char*`.

Which compiler do you use? Which compiler options do you use?

During development _SQLite3 Multiple Ciphers_ is compiled with various compilers, and the code compiles without problems.

BTW, I'm **not** condescending, when I tell you to carefully inspect the existing code. The details matter. If you look closely you will detect that the `CipherParams` structures are not allocated with the `const` attribute. And that has a reason, namely that the values are modifiable. Remove the `const` attribute, and the code should compile without error.

You may complain that the dynamic cipher scheme feature is not well documented. And you are right. However, originally the component was never meant to be extended by dynamic cipher schemes. It can well be that there are minor issues requiring small adjustments to the code.

> So using `nullptr` was the only way I could think of to fix that problem.

It's not the only possible solution. Using casts would be another option.

> It's the same reason I do the name string explicitly: the struct takes a `char*` as the cipher name, which means you can't use string literals, in C++ anyway.

_SQLite3 Multiple Ciphers_ consists of C code, not C++. You have to compile it in C mode

> In the C code you use macros and somehow this is able to get around that particular problem (or maybe it's compiling it in C mode).

Yes, it is C code and I would recommend to compile in C mode.

Or you adjust the code to be compilable in C++ mode. You are free to do that.

**Comment by ethindp** [comment]
> Which compiler do you use? Which compiler options do you use?
During development SQLite3 Multiple Ciphers is compiled with various compilers, and the code compiles without problems.

I am using MSVC 2022 in C++20 mode. The code that calls into SQLite3MC is C++ code. Removing the `const` qualifier does not actually resolve the compiler error. We are also compiling in non-permissive mode (`/permissive-`) since the project is cross-platform.

> SQLite3 Multiple Ciphers consists of C code, not C++. You have to compile it in C mode

I'm pretty sure that's what happens. This is a bug in my C++ code, though. If I c-style cast it to `char*` I obviously get a nasty crash at run-time. Does SQLite3MC ever modify these strings? If not it might be better to make them `const`.

**Comment by ethindp** [comment]
So I managed to hack it with std::string`, ironically enough. It works, I suppose. Not the solution I would like, but Idk what else to try other than to maybe move the cipher registration code into a C file.

**Comment by ethindp** [comment]
Aaaaaand I just realized that didn't solve it. Sigh.

**Comment by ethindp** [comment]
Okay,, I've resolved this problem, thank you fro the help :)

**Comment by utelle** [comment]
@ethindp **FYI**:

1. The signature of `GenerateKey` will change in the next version. The parameter `BtShared* pBt` will be removed from the parameter list. The parameter `cipherSalt` will point to a 16-byte buffer containing the key salt or will be a `NULL` pointer. If `cipherSalt` equals `NULL` or parameter `rekey` equals `1`, new random key salt must be generated.
2. The type of the `m_name` member of the `CipherParams` struct will change from `char*` to `const char*`. That is, you will hopefully not be forced any more to jump through hoops to avoid compile time problems with C++.

The next version of [SQLite](https://www.sqlite.org) is expected [next week](https://www.sqlite.org/draft/releaselog/3_47_0.html). A new version of _SQLite3 Multiple Ciphers_ will be released shortly thereafter (probably 1-3 days later).

**Comment by ethindp** [comment]
@utelle Thank you for the heads up. I did try implementing rekeying/salting support but I was getting very strange crashes (sigsegv) even though I'm pretty sure my boundaries were correct. Specifically, I was encrypting `data + 24.. (len - reserved)`. So I've temporarily just switched pack to encrypting the entire page without a salt. I'm not necessarily happy with it because it lowers the entropy of the keys, even with my use of HKDF, so I'm hoping to replace HKDF with Argon2 or something (but need to nail the salt problem first). I'll wait though until this next update since the work I'm doing isn't super critical and wait since I don't have any users of encrypted DB support quite yet.
