### ISSUE TITLE
Multiple calls to sqlite3_key

### ISSUE THREAD

**Issue by anperch** [utelle/SQLite3MultipleCiphers#18]
Hi,

My application using sqleet is opening a db, repeatedly calling sqlite3_key(db, pw, strlen(pw)) until the correct password is given and only closing the db on application exit.

Here is what happens with SQLite3MultipleCiphers:

- Opendb

- First call to sqlite3_key with a **wrong** password :
sqlite3_key <- **SQLITE_OK**
checking if the key is correct with "SELECT * FROM sqlite_master" gives -> "_File is not a database_"

- All following calls to sqlite3_key with a **wrong** password give :
sqlite3_key <- **SQLITE_OK**
checking if the key is correct  with "SELECT * FROM sqlite_master" gives -> "_database disk image is malformed_"

- Closedb

After the 2nd call to sqlite3_key, **the correct password is also not accepted anymore.**

Your documentation only says :
sqlite3_key() ... should _usually_ be called immediately after sqlite3_open().

So :
- Are multiple calls to sqlite3_key allowed without closing end reopening the db ?
- If not, would it be possible that sqlite3_key return an error on the second and the following calls ?

Thanks !

**Comment by utelle** [comment]
> * Are multiple calls to sqlite3_key allowed without closing end reopening the db ?

Well, the available documentation for the "official" SQLite encryption extension ([SEE](https://www.sqlite.org/see/doc/trunk/www/readme.wiki)) specifies no details, what should happen, when `sqlite3_key` is called multiple times. So, I could make it easy for myself and just answer _no_. However, as you observed **sqleet** allows to call `sqlite3_key` multiple times until the correct key is given eventually. And the predecessor of SQLite3MultipleCiphers, **wxSQLite3**, worked exactly the same as **sqleet**.

That said, it seems to be fair to call the current behavior of **SQLite3MultipleCiphers** a bug. However, I will have to inspect the code thoroughly once more, to find out, why a different error message is displayed after subsequent calls to `sqlite3_key` even if the correct key is given. I will certainly try to fix the problem, if it's technically possible.

> * If not, would it be possible that sqlite3_key return an error on the second and the following calls ?

`sqlite3_key` does not check whether the database is accessible with the given key. Only when accessing the database after a call to `sqlite3_key` it will be detected whether the correct key was given or not. And I hope I will be able to implement `sqlite3_key` in such a way that it can be called multiple times.

**Comment by utelle** [comment]
In the meantime I found out that `sqlite3_key` should reset the error state of the SQLite pager. Otherwise the database header is not read again with the new key set by further calls to `sqlite3_key`, when the database is accessed. 

After applying the modification mentioned above, the first call of `sqlite3_key` with an invalid key results in the error message _"File is not a database"_ as expected, but subsequent calls with invalid keys still result in the error message _"database disk image is malformed"_. Although this error message is in fact also correct, it would probably be better to be consistent.

**Comment by utelle** [comment]
Commit ece125fd8121d9bca67cd59be3830c896a98773e should now fix the issue. The error reported after providing an invalid key should now be consistently _"File is not a database"_. After eventually providing a valid key access to the database should no longer fail.

Reopen the issue if necessary.
