### ISSUE TITLE
Failed to make Windows 32bit Tcl extension with v1.1.4

### ISSUE THREAD

**Issue by yyamasak** [utelle/SQLite3MultipleCiphers#23]
The previous version I could successfully make was v1.0.0 with Tcl 8.6.10.  
This time, I tried to make v1.1.4 with Tcl 8.6.11 but it failed with error.  

Google implies it is related SSE. I'm not familiar with the code related to CPU...

[config.log](https://github.com/utelle/SQLite3MultipleCiphers/files/5885231/config.log)
[make.log](https://github.com/utelle/SQLite3MultipleCiphers/files/5885232/make.log)

Platform: Windows 10 Pro 20H2 64bit MSYS2 32bit

```bash
$ gcc --version
gcc.exe (Rev6, Built by MSYS2 project) 10.2.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by utelle** [comment]
I added code to enhance AES encryption performance. For GCC this requires to add proper machine options on invoking GCC. According to the information given in `make.log` you haven't done so.

For x86 architectures (as in your case) please add the following 2 GCC options:
```
-msse4.2 -maes 
```

Just for completeness, for ARM architectures please add the following GCC option:
```
-march=native 
```

**Comment by yyamasak** [comment]
Thank you.
I could successfully make it with the following configuration.

./configure --enable-threads --prefix=/c/bin/tcl8.6.11 --with-tcl=/c/src/tcl8.6.11/win CFLAGS="-DSQLITE_HAS_CODEC -DCODEC_TYPE=CODEC_TYPE_AES128 -DSQLITE_ENABLE_FTS5=1 -msse4.2 -maes"
