### ISSUE TITLE
Broken WAL mode in 1.3.0|1

### ISSUE THREAD

**Issue by lke-v** [utelle/SQLite3MultipleCiphers#39]
I was actually trying to replace sqlite3mc 1.1.1 with 1.3.1 using WAL mode and some old database, but stumbled upon some issues. After narrowing down I found that WAL mode in general seems to be broken in release 1.3.1 (or 1.3.0).
Run this to create a new database (in the sqlite3mc shell provided in the binary download for win64):
```
.open newtest-wal1.db
pragma cipher=chacha20;
pragma key='123';
pragma journal_mode=wal;
create table test (x int);
begin immediate;
insert into test (x) values (1);
commit;
select * from test;
```
and you still get a result, but after re-opening the database again:
```
.open
.open newtest-wal1.db
pragma cipher=chacha20;
pragma key='123';
select * from test;
```
we're lost with a broken db:
`Error: unsupported file format`

My original attempt was to model our application code and switch back out of WAL mode before closing the db:
```
.open
.open newtest-wal2.db
pragma cipher=chacha20;
pragma key='123';
pragma journal_mode=wal;
create table test (x int);
begin immediate;
insert into test (x) values (1);
commit;
select * from test;
pragma journal_mode=delete;
```
which also fails, but with a different error message:
`Error: database disk image is malformed`

**Comment by utelle** [comment]
Unfortunately I have to confirm the issue. Thanks for reporting. I will look into it to find out the cause of the problem.

**Comment by utelle** [comment]
I think I found the cause of the problem and hopefully fixed it with commit 43bd4366a33314addc1deb83e9898bef67d03295. 

On writing the WAL journal file the codec pointer was not determined correctly leading to a corrupted WAL journal. A small, but fatal mistake. I'm sorry for the inconveniences this may have caused.

Please verify that it now works for you. When I get a confirmation from you I will make a new release.

**Comment by lke-v** [comment]
I will let you know. Will take a little time because I want to make sure it also works in some other scenario I had problems with in 1.1.1

**Comment by utelle** [comment]
Take your time. Thanks for testing in real world scenarios.

**Comment by lke-v** [comment]
The point in case here seems to be fixed as you expected.
However I found another, probably unrelated issue, see #40. If (as I sincerely hope) there's a fix for that, too, I'd rather wait for a new release a bit more.

**Comment by utelle** [comment]
> The point in case here seems to be fixed as you expected.

I'm pretty confident that WAL journal mode now works as expected.

> However I found another, probably unrelated issue, see #40. If (as I sincerely hope) there's a fix for that, too, I'd rather wait for a new release a bit more.

Yes, that's understandable. And it is now more important to get things right than to publish just another broken release. I added a note to the release messages of version 1.3.0 and 1.3.1 that WAL journal mode is broken in those releases. Users of the default _Rollback Journal_ mode are not affected.

**Comment by utelle** [comment]
Release 1.3.2 fixes the underlying problems and provides a configuration parameter to facilitate the transition from prior versions. The documentation has been updated accordingly. Therefore this issue will be closed. Reopen it if necessary.
