### ISSUE TITLE
Download contains wrong version

### ISSUE THREAD

**Issue by richboss** [utelle/SQLite3MultipleCiphers#41]
The archive https://github.com/utelle/SQLite3MultipleCiphers/releases/download/v1.3.3/sqlite3mc-1.3.3-sqlite-3.36.0-win64.zip contains a shell binary which identifies as

    SQLite version 3.35.5 2021-04-19 18:32:05 (SQLite3 Multiple Ciphers 1.3.2)

The other archives of v1.3.3 are ok.

**Comment by utelle** [comment]
Thanks for reporting. I have updated the binary archive.
