### ISSUE TITLE
Assertion failure when compiled with `SQLITE_DEBUG`

### ISSUE THREAD

**Issue by m4heshd** [utelle/SQLite3MultipleCiphers#55]
What I wanted to know is if this is the intended behavior for Sqlitemc.

I'm compiling Sqlitemc with `SQLITE_DEBUG` set just for the tests. The assertion failure happens if you try to decrypt the DB with an incorrect passphrase (Sqleet) using `PRAGMA key` which exactly is the scenario I'm trying to test with Mocha. But since JS doesn't catch C++ runtime errors, the whole test process fails because of it.

```c
// Line 53647 in amalgamated sqlite3.c

case PAGER_READER:
  assert( pPager->errCode==SQLITE_OK ); //⬅ this one
  assert( p->eLock!=UNKNOWN_LOCK );
  assert( p->eLock>=SHARED_LOCK );
  break;
```

Was this `assert()` supposed fail on the above mentioned scenario? 🤔

**Comment by utelle** [comment]
> What I wanted to know is if this is the intended behavior for Sqlitemc.
> 
> I'm compiling Sqlitemc with `SQLITE_DEBUG` set just for the tests. The assertion failure happens if you try to decrypt the DB with an incorrect passphrase (Sqleet) using `PRAGMA key` which exactly is the scenario I'm trying to test with Mocha. But since JS doesn't catch C++ runtime errors, the whole test process fails because of it.
> 
> Was this `assert()` supposed fail on the above mentioned scenario? 🤔

When SQLite3MC fails to decrypt a database page, the error code of the SQLite pager is set to a value other than `SQLITE_OK`. However, most likely the error state of the SQLite pager should also be activated. Currently, the latter is not the case.

I will look into the error handling and I will try to adjust it to avoid the problem you experienced.

**Comment by m4heshd** [comment]
> I will look into the error handling and I will try to adjust it to avoid the problem you experienced.

Perfect. And thank you for the fast response, as always.

**Comment by utelle** [comment]
Commit 11a74620ba298f9ad4ad0791803e33a12c54851b should fix the issue.

A new release will be made shortly after the release of SQLite version 3.37.0 (expected in early December 2021).

**Comment by m4heshd** [comment]
Amazing. Such good news. I almost didn't report this since it's very niche but now I'm glad I brought this to your attention. Gracias. 👏🏼

**Comment by utelle** [comment]
The [latest release (version 1.3.5)](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.3.5) now includes this fix.

**Comment by m4heshd** [comment]
> The [latest release (version 1.3.5)](https://github.com/utelle/SQLite3MultipleCiphers/releases/tag/v1.3.5) now includes this fix.

Nice. [All tests](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/actions/runs/1515425193) are passing now.
