### ISSUE TITLE
Clang arm64 build errors

### ISSUE THREAD

**Issue by stuta** [utelle/SQLite3MultipleCiphers#67]
I was trying to compile in Windows 11 arm64 using https://github.com/mstorsjo/llvm-mingw. In Windows x64 build works, but arm64 build fails.

xmake f -p mingw -c --mingw=C:\prog\llvm-mingw-20220209-ucrt-aarch64 -a arm64

Also, arm64 in Linux with Clang had similar errors, GCC builds worked.

```bash
src/sqlite3patched.c:15677:22: warning: redefinition of typedef 'PgHdr' is a C11 feature [-Wtypedef-redefinition]
typedef struct PgHdr PgHdr;
                     ^
src/sqlite3patched.c:10384:22: note: previous definition is here
typedef struct PgHdr PgHdr;
                     ^
In file included from src\sqlite3mc.c:146:
In file included from src/rijndael.c:85:
src/aes_hardware.c:502:14: warning: implicit declaration of function 'vaeseq_u8' is invalid in C99 [-Wimplicit-function-declaration]
        v8 = vaeseq_u8(v8, vdupq_n_u8(0));
             ^
src/aes_hardware.c:502:12: error: assigning to 'uint8x16_t' (vector of 16 'uint8_t' values) from incompatible type 'int'
        v8 = vaeseq_u8(v8, vdupq_n_u8(0));
           ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/aes_hardware.c:565:26: warning: implicit declaration of function 'vaesimcq_u8' is invalid in C99 [-Wimplicit-function-declaration]
        keySchedule[j] = vaesimcq_u8(tempKeySchedule[j]);

... lots of other vaeseq_u8 related erros
```

**Comment by utelle** [comment]
> I was trying to compile in Windows 11 arm64 using https://github.com/mstorsjo/llvm-mingw. In Windows x64 build works, but arm64 build fails.

Unfortunately, I don't have currently access to any ARM64 system, neither macOS nor Windows.

> xmake f -p mingw -c --mingw=C:\prog\llvm-mingw-20220209-ucrt-aarch64 -a arm64

_MinGW_ is based on _gcc_, and therefore it will most likely need some compile flags to compile the AES hardware support code.

> Also, arm64 in Linux with Clang had similar errors, GCC builds worked.

Most likely _clang_ also needs a special compile flag.

> ```shell
> src/sqlite3patched.c:15677:22: warning: redefinition of typedef 'PgHdr' is a C11 feature [-Wtypedef-redefinition]
> typedef struct PgHdr PgHdr;
>                      ^
> src/sqlite3patched.c:10384:22: note: previous definition is here
> typedef struct PgHdr PgHdr;
>                      ^
> ```

As already mentioned in issue #66 I will address to eliminate this warning for the next release.

> ```shell
> In file included from src\sqlite3mc.c:146:
> In file included from src/rijndael.c:85:
> src/aes_hardware.c:502:14: warning: implicit declaration of function 'vaeseq_u8' is invalid in C99 [-Wimplicit-function-declaration]
>         v8 = vaeseq_u8(v8, vdupq_n_u8(0));
>              ^
> src/aes_hardware.c:502:12: error: assigning to 'uint8x16_t' (vector of 16 'uint8_t' values) from incompatible type 'int'
>         v8 = vaeseq_u8(v8, vdupq_n_u8(0));
>            ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> src/aes_hardware.c:565:26: warning: implicit declaration of function 'vaesimcq_u8' is invalid in C99 [-Wimplicit-function-declaration]
>         keySchedule[j] = vaesimcq_u8(tempKeySchedule[j]);
> 
> ... lots of other vaeseq_u8 related erros
> ```

When an ARM platform has been detected, the header file `arm_neon.h` (or `arm64_neon.h`) will be included (line 414 / 412 in `aes_hardware.c`). This header file should declare the functions for which the warnings of implicit declaration are issued. Please check which header file is actually included and whether it contains declarations for the functions in question or not.

**Comment by stuta** [comment]
If I add define USE_ARM64_NEON_H and copy [header file](https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/km/crt/arm64_neon.h) then there are no errors in the compilation. 

Problems come with linking: `ld.lld: error: undefined symbol: neon_st1m_q8` and others starting with neon. I tried to find info about needed library, but I could not find it. Maybe Clang does not support neon 64 yet.

**Comment by stuta** [comment]
Clang has arm_neon.h, but without arm64_neon.h it created those errors.

I found this repo, maybe it has some info to help: https://github.com/DLTcollab/sse2neon.

**Comment by stuta** [comment]
I had to re-create my Linux virtual machine. I added GCC first and then Clang and now I can compile also with Clang. Linux is not a problem, GCC works in Linux with arm64.

The problem has been Windows 11 and arm64 (Apple M1 in Parallels). If I add USE_ARM64_NEON_H define and arm64_neon.h to Clang include folder then there are no compile errors. But I get linker errors:

```bash
error: ld.lld: error: undefined symbol: neon_st1m_q8
>>> referenced by build\.objs\sqlite3mc\mingw\aarch64\release\src\sqlite3mc.c.obj:(aesGenKeyEncrypt)
>>> referenced by build\.objs\sqlite3mc\mingw\aarch64\release\src\sqlite3mc.c.obj:(aesGenKeyDecrypt)
>>> referenced by build\.objs\sqlite3mc\mingw\aarch64\release\src\sqlite3mc.c.obj:(aesEncryptCBC)
>>> referenced 7 more times

ld.lld: error: undefined symbol: neon_aesimc
>>> referenced by build\.objs\sqlite3mc\mingw\aarch64\release\src\sqlite3mc.c.obj:(aesGenKeyDecrypt)
>>> referenced by build\.objs\sqlite3mc\mingw\aarch64\release\src\sqlite3mc.c.obj:(aesDecryptCBC)
>>> referenced by build\.objs\sqlite3mc\mingw\aarch64\release\src\sqlite3mc.c.obj:(aesDecryptCBC)
>>> referenced 1 more times
...
```

This is not a big problem now because Windows 11 can run x64 programs.

**Comment by utelle** [comment]
> I had to re-create my Linux virtual machine. I added GCC first and then Clang and now I can compile also with Clang. Linux is not a problem, GCC works in Linux with arm64.

In the meantime I added CI jobs for ARM architectures and verified that the builds work under Ubuntu-20.04. Additionally, I modified the source code in commit 9c5eddc60065d9bd560d52253ce2455c84d11662, so that the reported warning should now be eliminated.

> The problem has been Windows 11 and arm64 (Apple M1 in Parallels). If I add USE_ARM64_NEON_H define and arm64_neon.h to Clang include folder then there are no compile errors.

Since I don't have access to a system with such a combination, I can't help to resolve this issue. As said before _clang_ typically uses `arm_neon.h`. Only Microsoft renamed that include file to `arm64_neon.h` for Visual C++ and ARM64.

> But I get linker errors:

That should not happen. AFAIK the compiler transforms the neon intrinsics into machine instructions not requiring additional link libraries.

> This is not a big problem now because Windows 11 can run x64 programs.

At least that is a workaround.
