### ISSUE TITLE
Build fails with the latest release when built in debug mode

### ISSUE THREAD

**Issue by m4heshd** [utelle/SQLite3MultipleCiphers#74]
The build fails with the following error:

```
sqlite3.c:273888:31: error: ‘mcVfsGlobal’ undeclared (first use in this function); did you mean ‘mcVfsSleep’?
   assert(p->pMainNext == 0 && mcVfsGlobal.pMain != p);
```

You can take a look at [this run](https://github.com/m4heshd/better-sqlite3-multiple-ciphers/runs/6191283275?check_suite_focus=true#step:5:52) to inspect the error in depth.

**Comment by utelle** [comment]
Sorry, I simply forgot to replace the reference to `mcVfsGlobal` in the `assert` statement with the new structure.

Strange enough Visual C++ compiles the code in debug mode without any error or warning message.
Commit 91c7cd625ec279fb70c9c87b3704dfcf760951f3 should fix the problem.

**Comment by m4heshd** [comment]
Perfect. Thank you so much for the very fast patch. I'm gonna wait for a release to run a test on bs3mc. I'll leave the issue open till the next release in case somebody else run into this issue. 😊

**Comment by utelle** [comment]
I just made a new release. Sorry for the inconveniences.

**Comment by m4heshd** [comment]
> Sorry for the inconveniences.

That was no trouble at all.

All tests ran perfectly. Thank you again. ❤️
