### ISSUE TITLE
iOS Build Error 'sys/random.h' file not found

### ISSUE THREAD

**Issue by Nailik** [utelle/SQLite3MultipleCiphers#92]
When building on Mac OS for an iOS device there is an error in sqlite3.c (amalgamation file).

sqlite3.c fatal error: 'sys/random.h' file not found
#include <sys/random.h>

After removing the line, it builds and works.

**Comment by utelle** [comment]
The inclusion of the header file is guarded by the following preprocessor instruction:
```C
#if defined(__APPLE__) && defined(__MAC_10_12)
#include <sys/random.h>
#endif
```
So, even though you are compiling for iOS both symbols seem to be defined, and the compiler therefore tries to include the header file `sys/random.h`.

You could try to modify the check as follows:

```C
#if defined(__APPLE__) && defined(__MAC_10_12) && !defined(__IPHONE_OS_VERSION_MIN_REQUIRED)
#include <sys/random.h>
#endif
```
Most likely this will prevent the inclusion of the header file for the iOS build. Please let me know whether this works for you.

**Comment by Nailik** [comment]
This fixed the issue!

**Comment by utelle** [comment]
Thanks for confirming. Commit a8c9e93ef51a700d3e96c1b020a10e7c9622eabb applies the fix.
